"""ADD

Revision ID: 1c0c19939433
Revises: 9076f7f1d1f1
Create Date: 2022-11-01 17:40:51.760672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0c19939433'
down_revision = '9076f7f1d1f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
