"""ADD

Revision ID: bc92af976813
Revises: 1c0c19939433
Create Date: 2022-11-02 10:07:25.008506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc92af976813'
down_revision = '1c0c19939433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_table_id'), 'token_table', ['id'], unique=False)
    op.create_foreign_key(None, 'business', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'business', 'states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'userdetail', 'cities', ['state_id'], ['id'])
    op.create_foreign_key(None, 'userdetail', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdetail', type_='foreignkey')
    op.drop_constraint(None, 'userdetail', type_='foreignkey')
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_index(op.f('ix_token_table_id'), table_name='token_table')
    op.drop_table('token_table')
    # ### end Alembic commands ###
